---
title: 'cinematic music'
subtitle: 'alternative soundtracks'
---

---

### Transcendental Cinema

<iframe src="https://player.vimeo.com/video/1078969824?h=8fdba15209&title=0&byline=0&portrait=0" width="600" height="336" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>

Film: **Gravity** (Alfonso Cuarón, 2013)\
Audio: Sigur Rós, "Ágætis Byrjun" (**Ágætis Byrjun**, 1999)

Sigur Rós's music is profoundly cinematic. I have loved the title song from their second album since first hearing it in the late 1990s, but only recently had the idea of using it to score the extraordinary closing sequence from Alfonso Cuarón's film **Gravity**. I'm not sure how well it works, but the music lifts the sequence to the level of what Paul Schrader famously called **transcendental cinema**. 

---

### Fauré's Pavane

Alfreda Benga worked as second assistant editor on the production of Nicolas Roeg's classic thriller, **Don't Look Now** (1973), set in Venice: 

> My job was just to log all the film as it came in . . . so any shot needed could be given to Graeme [Clifford], the editor, as he needed it. It was just creating some order and keeping order. Graeme would be on the editing machine. Tony Lawson was the first assistant. Nic would come in to check how it was going. They’d often watch sequences to existing music that was later replaced by Pino Donaggio’s score. I have a strong memory of the funeral scene with Fauré’s **Pavane**, which worked beautifully”.<br><br>---Glenn Kenny, "[Two Intertwined Semi-Venetian Masterpieces](https://www.criterion.com/current/posts/3591-two-intertwined-semi-venetian-masterpieces?srsltid=AfmBOoraDEIB8oTxamsIxzVjxUIx0o_GlQcmMzodyFUm51g4oRXn96fZ)" (**Criterion Collection**, 7 June 2015).

The full title of the Fauré piece is **Pavane pour une infante défunte** \[Pavane for a deceased child\]---an eerily appropriate title for a film that revolves around the death of a child. I decided to see how the funeral scene looked with the Fauré piece that was originally used before it was replaced by Pino Donaggio's score.

<iframe src="https://player.vimeo.com/video/891052187?h=8fdba15209&title=0&byline=0&portrait=0" width="600" height="336" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>

Film: **Don't Look Now** (dir. Nicolas Roeg, 1973)\
Music: Fauré, **Pavane pour une infante défunte** (1899), Op. 50 (solo piano version)\
Piano: Jorge Federico Osorio\
Recording: **The French Album** (Cedille, 2020)

---

### Langsames Kino

<br><iframe src="https://player.vimeo.com/video/808559077?h=8fdba15209&title=0&byline=0&portrait=0" width="600" height="336" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>

In mid-January 2023, I came across a brilliant photoessay titled “[The Defence of Lützerath](https://crimethinc.com/2023/01/19/the-defense-of-lutzerath-a-photoessay-and-poster-documenting-ecological-destruction-and-resistance),” about an ongoing standoff in Germany between riot police and environmental activists peacefully trying to prevent the destruction of the village of Lützerath to create an open-pit coal mine. The photoessay led me to a [recently-posted video](https://youtu.be/oEAD402r8Rs) documenting the conflict on YouTube. The video depicted surreal scenes of riot police struggling to control the large crowd of protesters under difficult conditions, getting bogged down, ridiculed, and pelted with mud. The scene seemed like some kind of sublime metaphor for the futility of human existence and I found myself remembering Werner Herzog’s similar fascination with sublime horror in his documentary about the aftermath of the Kuwait war, [Lessons of Darkness](https://youtu.be/xDfo71gRb8A) (1992), and other documentaries.

I wanted to use some kind of choral soundtrack to emphasize the scene’s almost mythic grandeur, and eventually settled on the fourth movement of Mahler’s Symphony No. 3, used in [a very different sequence](https://youtu.be/6-42QSSYrGE) of one of my favorite films, Luchino Visconti’s **Death in Venice** (1971). The movement includes a magnificent song whose lyrics are the poem [Zarathustra’s Rundgesang](https://en.wikipedia.org/wiki/Zarathustra%27s_roundelay) [Zarathustra’s Roundelay], from Nietzsche’s **Also Sprach Zarathustra** (1883-85)—a text that also inspired a better-known cinematic encounter, Richard Strauss’s tone poem used in Stanley Kubrick’s [**2001: A Space Odyssey**](https://youtu.be/WufKsOhkTL8) (1968). The song’s lyrics—the poem from Nietzsche’s text—are included on the [Vimeo page](https://vimeo.com/808559077) for the video above.

The resulting video is thus a four-part homage to Nietzsche, Mahler, Visconti, and Herzog (or maybe five, if you include Kubrick). Watching it again with Mahler’s soundtrack, it occurs to me that it could be seen as a kind of slow cinema (or _langsames Kino_ in German) and it’s appropriate that the movement’s tempo instruction is _Sehr langsam—misterioso_ [very slow—mysterious]. It might be interesting to slow down the video to emphasize this quality, but thanks to the mud the events already seem to be unfolding in slow motion.

---

### Underworld

This was originally an assignment for my course at Emerson College, VM402-09 Soundtracks: Music & Audiovisual Media, taught in Spring 2019. The first two videos were produced as demos for the assignment. I’ve added a couple of other examples of a film and a student-made music video that also exemplify the alternate-soundtrack concept.

<iframe src="https://player.vimeo.com/video/700577451?h=f41931040f&color=59C4A2&title=0&byline=0&portrait=0" width="600" height="336" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>

Mica Levi’s [score](https://www.theguardian.com/music/2014/mar/15/mica-levi-under-the-skin-soundtrack) for Jonathan Glazer’s eerie sci-fi film **Under The Skin** (2013) is atonal and appropriately alien. I was fascinated by the sequences of the film in which the alien played by Scarlett Johansson lures unsuspecting Scotsmen to their doom in some kind of amber-like underworld, which was visually remarkably similar to the “Sunken Place” sequence in Jordan Peele’s **Get Out** (2017). My original idea was to juxtapose the two films, but the Radiohead track fitted the **Under The Skin** sequence so perfectly that it seemed like overkill to include anything else.

Film: **Under the Skin** (Jonathan Glazer, 2012)\
Music: Radiohead, “Everything In Its Right Place” (Kid A, Capitol Records, 2000)

---

### Superior Mirages

<br><iframe src="https://player.vimeo.com/video/700581439?h=2668187516&color=59C4A2&title=0&byline=0&portrait=0" width="600" height="336" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>

From 1969-72, the UK psychedelic group Pink Floyd composed soundtracks for a number of films, including Barbet Schroeder’s **More** (1969), Michelangelo Antonioni’s **Zabriskie Point** (1970), and Barbet Schroeder’s **La Vallée** (1972) (the latter subsequently released as the album **Obscured by Clouds** (Harvest, 1972).

Around the same time, the German filmmaker Werner Herzog was collaborating with the krautrock band [Popol Vuh](https://thequietus.com/articles/16110-herzog-popol-vuh-overview) on the scores of **Aguirre, the Wrath of God** (1972), **Heart of Glass** (1976), **Nosferatu** (1979), **Fitzcarraldo** (1982) and **Cobra Verde** (1987).

Since Herzog’s film about [superior mirages](https://www.theguardian.com/science/2021/mar/05/ship-hovering-above-sea-cornwall-optical-illusion), **Fata Morgana** (1971), shot in the desolate Sahel region of Central Africa, pre-dates his collaboration with Popol Vuh, and Pink Floyd never collaborated with Herzog, I decided to imagine such a collaboration on **Fata Morgana**.

Film: **Fata Morgana** (Werner Herzog, 1971)

Music: Pink Floyd, “Shine On You Crazy Diamond (Part 8)” (Wish You Were Here, Columbia, 1975)

---

### Man With A Movie Camera

<br><iframe src="https://player.vimeo.com/video/708401254?h=e2f3a74494&color=59C4A2&title=0&byline=0&portrait=0" width="600" height="336" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>

Film: **Man With A Movie Camera** (Dziga Vertov, 1929)\
Music: Cinematic Orchestra (**Man With A Movie Camera**, Ninja Tune, 2003)

I didn’t make this one - it’s one of a number of alternate soundtracks composed for Dziga Vertov’s classic of Soviet montage, this one by the U.K. band The Cinematic Orchestra. The soundtrack brilliantly complements the rhythmic montage of Vertov’s portrait of everyday life in post-revolutionary Russia. I used it as one of the clips in the final exam of my course (COMM 232 Understanding Film at Franklin Pierce University, taught in Spring 2022.

---

### Subterranean Homesick Alien

<br><iframe width="600" height="336" src="https://www.youtube.com/embed/2Y6Obk_WeC0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Music video: uncredited student project\
Music: Radiohead, “Subterranean Homesick Alien” (**OK Computer**, XL Recordings, Ltd., 1997)

---

### Guinnevere

<br><iframe src="https://player.vimeo.com/video/709942445?h=e2f3a74494&color=59C4A2&title=0&byline=0&portrait=0" width="600" height="336" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>

Video: **DEVS** (Alex Garland, 2020), Episode 6, opening credits\
Music: Crosby, Stills, & Nash, “Guinnevere” (**Crosby, Stills, & Nash**, Atlantic, 1969)

---

[Martin Roberts](mailto:dokoissho.sdf.org) 2019-25